import { redirect } from "next/navigation";
import { logout, uploadImage } from "@/app/admin/actions";
import { ResourceManager, type AdminField } from "@/components/admin/ResourceManager";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";

const commonFields: AdminField[] = [{ name: "published", label: "Đang hiển thị", type: "checkbox" }, { name: "verified", label: "Đã xác minh", type: "checkbox" }];
const branchFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên cơ sở", required: true }, { name: "area", label: "Khu vực", required: true }, { name: "address", label: "Địa chỉ", type: "textarea", required: true }, { name: "map_url", label: "Google Maps URL" }, { name: "phone", label: "Hotline" }, { name: "opening_hours", label: "Giờ mở cửa" }, { name: "status", label: "Trạng thái", type: "select", options: ["active", "temporarily-closed", "unverified"] }, { name: "description", label: "Mô tả", type: "textarea" }, { name: "image_url", label: "URL ảnh" }, { name: "image_alt", label: "Alt ảnh" }, { name: "sort_order", label: "Thứ tự", type: "number" }, ...commonFields];
const promotionFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên combo", required: true }, { name: "price", label: "Giá", type: "number", required: true }, { name: "highlights", label: "Điểm nổi bật (mỗi dòng một ý)", type: "textarea" }, { name: "note", label: "Ghi chú", type: "textarea" }, { name: "image_url", label: "URL ảnh" }, { name: "valid_from", label: "Bắt đầu", type: "date" }, { name: "valid_until", label: "Kết thúc", type: "date" }, { name: "featured", label: "Nổi bật", type: "checkbox" }, ...commonFields];
const tournamentFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên giải", required: true }, { name: "game", label: "Game", type: "select", options: ["FC Online", "Valorant", "TFT", "AOE"] }, { name: "description", label: "Mô tả", type: "textarea" }, { name: "held_on", label: "Ngày tổ chức", type: "date" }, { name: "branch_name", label: "Cơ sở" }, { name: "placements", label: "Top 1–3 (JSON)", type: "textarea" }, { name: "image_url", label: "URL ảnh" }, { name: "image_alt", label: "Alt ảnh" }, ...commonFields];
const memberFields: AdminField[] = [{ name: "display_name", label: "Nickname rút gọn", required: true }, { name: "tier", label: "Hạng", type: "select", options: ["Diamond", "Platinum", "Gold"] }, { name: "period_label", label: "Tháng vinh danh" }, { name: "image_url", label: "URL ảnh" }, { name: "image_alt", label: "Alt ảnh" }, { name: "consent_confirmed", label: "Khách đã đồng ý công khai", type: "checkbox" }, ...commonFields];
const galleryFields: AdminField[] = [{ name: "title", label: "Tiêu đề", required: true }, { name: "image_url", label: "URL ảnh", required: true }, { name: "image_alt", label: "Alt ảnh", required: true }, { name: "bucket", label: "Bucket", type: "select", options: ["hero", "branches", "community", "hall-of-fame", "members"] }, { name: "sort_order", label: "Thứ tự", type: "number" }, ...commonFields];
const siteImageFields: AdminField[] = [{ name: "image_key", label: "Khóa ảnh", required: true }, { name: "bucket", label: "Bucket", required: true }, { name: "object_path", label: "Đường dẫn object", required: true }, { name: "public_url", label: "URL công khai", required: true }, { name: "alt_text", label: "Alt ảnh", required: true }, ...commonFields];

type Row = Record<string, unknown>;

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  if (!isSupabaseConfigured()) redirect("/admin/login?error=config");
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/admin/login");
  const { data: membership } = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle();
  if (!membership) redirect("/admin/login?error=permission");
  const tables = ["branches", "promotions", "tournaments", "hall_of_fame_members", "site_images", "gallery_items"] as const;
  const results = await Promise.all(tables.map((table) => supabase.from(table).select("*").order("created_at", { ascending: false })));
  const data = Object.fromEntries(tables.map((table, index) => [table, (results[index].data ?? []) as Row[]])) as Record<(typeof tables)[number], Row[]>;
  const { error } = await searchParams;
  const loadError = results.find((result) => result.error)?.error?.message;
  const visibleError = error === "invalid-image" ? "Ảnh phải là JPEG, PNG hoặc WebP và không vượt quá 5MB." : error === "placements-json" ? "Dữ liệu Top 1–3 phải là JSON hợp lệ." : error;

  return <main className="mx-auto max-w-6xl space-y-14 px-5 py-8 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-xs font-bold uppercase tracking-widest text-tiger-orange">Tiger Esports</p><h1 className="mt-2 text-3xl font-extrabold">Dashboard nội dung</h1><p className="mt-1 text-sm text-zinc-500">{user.email}</p></div><form action={logout}><button className="min-h-11 rounded-lg border border-white/15 px-4 text-sm font-bold">Đăng xuất</button></form></header>{visibleError || loadError ? <p className="rounded-lg border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{visibleError ?? `Không thể tải dữ liệu: ${loadError}`}</p> : null}<section className="rounded-2xl border border-tiger-orange/25 bg-tiger-orange/5 p-5"><h2 className="text-2xl font-extrabold">Upload ảnh</h2><p className="mt-2 text-sm text-zinc-500">JPEG, PNG hoặc WebP, tối đa 5MB. Ảnh mới luôn ở trạng thái chưa xuất bản.</p><form action={uploadImage} className="mt-5 grid gap-3 md:grid-cols-2"><select name="bucket" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3"><option>hero</option><option>branches</option><option>community</option><option>hall-of-fame</option><option>members</option></select><input name="image_key" placeholder="Khóa ảnh, ví dụ hero-main" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3" /><input name="alt_text" placeholder="Mô tả ảnh" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3" /><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 p-2" /><button className="min-h-11 rounded-lg bg-tiger-orange font-bold md:col-span-2">Upload lên Storage</button></form></section><ResourceManager title="Cơ sở" resource="branches" fields={branchFields} records={data.branches} /><ResourceManager title="Combo & khuyến mãi" resource="promotions" fields={promotionFields} records={data.promotions} /><ResourceManager title="Giải đấu" resource="tournaments" fields={tournamentFields} records={data.tournaments} /><ResourceManager title="Hội viên vinh danh" resource="hall_of_fame_members" fields={memberFields} records={data.hall_of_fame_members} /><ResourceManager title="Ảnh website" resource="site_images" fields={siteImageFields} records={data.site_images} /><ResourceManager title="Gallery" resource="gallery_items" fields={galleryFields} records={data.gallery_items} /></main>;
}
