import { redirect } from "next/navigation";
import { logout, uploadImage } from "@/app/admin/actions";
import { ResourceManager, type AdminField } from "@/components/admin/ResourceManager";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";

const commonFields: AdminField[] = [{ name: "published", label: "Đang hiển thị", type: "checkbox" }, { name: "verified", label: "Đã xác minh", type: "checkbox" }];
const branchFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên cơ sở", required: true }, { name: "area", label: "Khu vực", required: true }, { name: "address", label: "Địa chỉ", type: "textarea", required: true }, { name: "map_url", label: "Google Maps URL" }, { name: "phone", label: "Hotline" }, { name: "opening_hours", label: "Giờ mở cửa" }, { name: "status", label: "Trạng thái", type: "select", options: ["active", "temporarily-closed", "unverified"] }, { name: "description", label: "Mô tả", type: "textarea" }, { name: "image_url", label: "Ảnh cơ sở", type: "image" }, { name: "image_alt", label: "Alt ảnh" }, { name: "sort_order", label: "Thứ tự", type: "number" }, ...commonFields];
const promotionFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên combo", required: true }, { name: "price", label: "Giá", type: "number", required: true }, { name: "highlights", label: "Điểm nổi bật (mỗi dòng một ý)", type: "textarea" }, { name: "note", label: "Ghi chú", type: "textarea" }, { name: "image_url", label: "Ảnh combo", type: "image" }, { name: "valid_from", label: "Bắt đầu", type: "date" }, { name: "valid_until", label: "Kết thúc", type: "date" }, { name: "featured", label: "Nổi bật", type: "checkbox" }, ...commonFields];
const tournamentFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên giải", required: true }, { name: "game", label: "Game", type: "select", options: ["FC Online", "Valorant", "TFT", "AOE"] }, { name: "status", label: "Trạng thái", type: "select", options: ["upcoming", "registration_open", "ongoing", "completed"] }, { name: "description", label: "Mô tả", type: "textarea" }, { name: "rules", label: "Thể lệ", type: "textarea" }, { name: "held_on", label: "Ngày tổ chức", type: "date" }, { name: "starts_at", label: "Bắt đầu", type: "datetime-local" }, { name: "ends_at", label: "Kết thúc", type: "datetime-local" }, { name: "branch_name", label: "Cơ sở" }, { name: "entry_fee", label: "Lệ phí", type: "number" }, { name: "registration_url", label: "URL đăng ký", type: "url" }, { name: "registration_open", label: "Mở đăng ký", type: "checkbox" }, { name: "top_1", label: "Top 1" }, { name: "top_2", label: "Top 2" }, { name: "top_3", label: "Top 3" }, { name: "image_url", label: "Ảnh giải đấu", type: "image" }, { name: "image_alt", label: "Alt ảnh" }, { name: "video_url", label: "Video / recap", type: "video" }, { name: "video_provider", label: "Nguồn video", type: "select", options: ["upload", "youtube", "facebook", "external"] }, { name: "poster_url", label: "Ảnh poster video", type: "image" }, ...commonFields];
const memberFields: AdminField[] = [{ name: "display_name", label: "Nickname rút gọn", required: true }, { name: "tier", label: "Hạng", type: "select", options: ["Diamond", "Platinum", "Gold"] }, { name: "period_label", label: "Tháng vinh danh" }, { name: "image_url", label: "Ảnh hội viên", type: "image" }, { name: "image_alt", label: "Alt ảnh" }, { name: "consent_confirmed", label: "Khách đã đồng ý công khai", type: "checkbox" }, ...commonFields];
const galleryFields: AdminField[] = [{ name: "title", label: "Tiêu đề", required: true }, { name: "caption", label: "Chú thích", type: "textarea" }, { name: "media_type", label: "Loại media", type: "select", options: ["image", "video"] }, { name: "image_url", label: "Ảnh gallery", type: "image" }, { name: "image_alt", label: "Alt ảnh" }, { name: "video_url", label: "Video", type: "video" }, { name: "video_provider", label: "Nguồn video", type: "select", options: ["upload", "youtube", "facebook", "external"] }, { name: "poster_url", label: "Ảnh poster video", type: "image" }, { name: "bucket", label: "Bucket ảnh", type: "select", options: ["hero", "branches", "community", "hall-of-fame", "members"] }, { name: "sort_order", label: "Thứ tự", type: "number" }, ...commonFields];
const siteImageFields: AdminField[] = [{ name: "image_key", label: "Khóa ảnh", required: true }, { name: "bucket", label: "Bucket", required: true }, { name: "object_path", label: "Đường dẫn object", required: true }, { name: "public_url", label: "URL công khai", required: true }, { name: "alt_text", label: "Alt ảnh", required: true }, ...commonFields];
const pcTierFields: AdminField[] = [{ name: "slug", label: "Slug", required: true }, { name: "name", label: "Tên hạng máy", required: true }, { name: "subtitle", label: "Mô tả ngắn" }, { name: "cpu", label: "CPU", required: true }, { name: "gpu", label: "GPU", required: true }, { name: "ram", label: "RAM", required: true }, { name: "monitor", label: "Màn hình", required: true }, { name: "mainboard", label: "Mainboard" }, { name: "storage", label: "Ổ cứng" }, { name: "peripherals", label: "Thiết bị ngoại vi", type: "textarea" }, { name: "note", label: "Ghi chú", type: "textarea" }, { name: "branch_scope", label: "Phạm vi cơ sở" }, { name: "sort_order", label: "Thứ tự", type: "number" }, { name: "featured", label: "Nổi bật", type: "checkbox" }, ...commonFields];

type Row = Record<string, unknown>;

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  if (!isSupabaseConfigured()) redirect("/admin/login?error=config");
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/admin/login");
  const { data: membership } = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle();
  if (!membership) redirect("/admin/login?error=permission");
  const tables = ["branches", "promotions", "tournaments", "hall_of_fame_members", "site_images", "gallery_items", "pc_tiers"] as const;
  const results = await Promise.all(tables.map((table) => supabase.from(table).select("*").order("created_at", { ascending: false })));
  const data = Object.fromEntries(tables.map((table, index) => [table, (results[index].data ?? []) as Row[]])) as Record<(typeof tables)[number], Row[]>;
  const tournamentRecords = data.tournaments.map((record) => {
    const placements = Array.isArray(record.placements) ? record.placements as Array<Record<string, unknown>> : [];
    return { ...record, top_1: placements.find((placement) => placement.position === 1)?.displayName ?? "", top_2: placements.find((placement) => placement.position === 2)?.displayName ?? "", top_3: placements.find((placement) => placement.position === 3)?.displayName ?? "" };
  });
  const { error } = await searchParams;
  const loadError = results.find((result) => result.error)?.error?.message;
  const errorMessages: Record<string, string> = { "invalid-image": "Ảnh phải là JPEG, PNG hoặc WebP và không vượt quá 5MB.", "invalid-video": "Video phải là MP4 hoặc WebM và không vượt quá 25MB.", "invalid-media-bucket": "Bucket media không hợp lệ hoặc migration video chưa được kích hoạt.", "publish-requires-verified": "Không thể công khai nội dung khi chưa bật Đã xác minh.", "invalid-image-url": "URL ảnh phải là đường dẫn /images hoặc URL Supabase Storage hợp lệ.", "invalid-poster-url": "URL poster phải là đường dẫn /images hoặc URL Supabase Storage hợp lệ.", "invalid-video-url": "URL video phải bắt đầu bằng http:// hoặc https://.", "gallery-image-required": "Gallery loại ảnh cần ảnh hoặc file ảnh.", "gallery-video-required": "Gallery loại video cần URL hoặc file video.", "invalid-registration-url": "URL đăng ký phải bắt đầu bằng http:// hoặc https://.", "registration-url-required": "Giải mở đăng ký bắt buộc có URL đăng ký.", "member-consent-required": "Không thể công khai hội viên khi chưa xác nhận đồng ý." };
  const visibleError = error ? errorMessages[error] ?? error : undefined;

  return <main className="mx-auto max-w-6xl space-y-14 px-5 py-8 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-xs font-bold uppercase tracking-widest text-tiger-orange">Tiger Esports</p><h1 className="mt-2 text-3xl font-extrabold">Dashboard nội dung</h1><p className="mt-1 text-sm text-zinc-500">{user.email}</p></div><form action={logout}><button className="min-h-11 rounded-lg border border-white/15 px-4 text-sm font-bold">Đăng xuất</button></form></header>{visibleError || loadError ? <p className="rounded-lg border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{visibleError ?? `Không thể tải dữ liệu: ${loadError}`}</p> : null}<section className="rounded-2xl border border-tiger-orange/25 bg-tiger-orange/5 p-5"><h2 className="text-2xl font-extrabold">Upload ảnh</h2><p className="mt-2 text-sm text-zinc-500">JPEG, PNG hoặc WebP, tối đa 5MB. Ảnh mới luôn ở trạng thái chưa xuất bản.</p><form action={uploadImage} className="mt-5 grid gap-3 md:grid-cols-2"><select name="bucket" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3"><option>hero</option><option>branches</option><option>community</option><option>hall-of-fame</option><option>members</option></select><input name="image_key" placeholder="Khóa ảnh, ví dụ hero-main" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3" /><input name="alt_text" placeholder="Mô tả ảnh" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 px-3" /><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required className="min-h-11 rounded-lg border border-white/10 bg-black/50 p-2" /><button className="min-h-11 rounded-lg bg-tiger-orange font-bold md:col-span-2">Upload lên Storage</button></form></section><ResourceManager title="Cơ sở" resource="branches" fields={branchFields} records={data.branches} /><ResourceManager title="Combo & khuyến mãi" resource="promotions" fields={promotionFields} records={data.promotions} /><ResourceManager title="Dàn máy / Cấu hình" resource="pc_tiers" fields={pcTierFields} records={data.pc_tiers} /><ResourceManager title="Giải đấu" resource="tournaments" fields={tournamentFields} records={tournamentRecords} /><ResourceManager title="Hội viên vinh danh" resource="hall_of_fame_members" fields={memberFields} records={data.hall_of_fame_members} /><ResourceManager title="Ảnh website" resource="site_images" fields={siteImageFields} records={data.site_images} /><ResourceManager title="Gallery" resource="gallery_items" fields={galleryFields} records={data.gallery_items} /></main>;
}
